Parse server fix applied
MoralisWeb3/web3-unity-sdk pull request #67
Opened 2023-01-10 11:23 UTC by dpradell-moralis

Applied changes documented in the following post:
https://forum.moralis.io/t/using-unity-sdk-with-self-hosted-server/20527

Tested in Editor and WebGL.

2023-01-10 13:24 UTC, xactant requested changes
Had some comments

2023-01-10 13:24 UTC, xactant commented on Runtime/Kits/AuthenticationKit/Scripts/AuthenticationKit.cs
> +                    if (serverTimeResponse != null)
Please confirm this condition is correct - it looks like it will throw the error if server time is returned.

2023-01-10 13:24 UTC, xactant commented on Runtime/Kits/AuthenticationKit/Scripts/AuthenticationKit.cs
> +            if (serverTimeResponse != null)
Please confirm this condition is correct - it looks like it will throw the error if server time is returned.

2023-01-10 13:34 UTC, dpradell-moralis commented on Runtime/Kits/AuthenticationKit/Scripts/AuthenticationKit.cs
> +            if (serverTimeResponse != null)
Yes, that's correct. That's because [self hosted parse server returns null](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/demos/parse-server-migration/src/cloud/main.ts#L25) when `getServerTime` is called. Since this SDK is mainly supporting v1-self-hosted-server users I figured it would be good to make the change.

2023-01-10 14:10 UTC, dpradell-moralis commented
Changes applied

2023-01-10 18:04 UTC, dFohlen commented
Hi @dpradell-moralis,

just a comment from my side. I'm trying to apply these changes and got the following error after that:

Unity Logs:
```
Error: HTTP/1.1 400 Bad Request
{"code":141,"error":"Invalid function: \"requestMessage\""}
UnityEngine.Debug:LogError (object)
MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7:MoveNext () (at Assets/MoralisSDK/Runtime/Core/Platform/Services/ClientServices/UniversalWebClient.cs:91)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2<MoralisUnity.Platform.Services.UniversalWebClient/<ExecuteAsync>d__7, System.Tuple`2<System.Net.HttpStatusCode, string>>:Run () (at Assets/MoralisSDK/Runtime/External/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:313)
Cysharp.Threading.Tasks.Internal.PooledDelegate`1<UnityEngine.AsyncOperation>:Run (UnityEngine.AsyncOperation) (at Assets/MoralisSDK/Runtime/External/UniTask/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/AsyncOperation.cs:21)
```
Running in the Unity editor.

Server Logs:
```
root@ubuntu-4gb-nbg1-1:~/moralis/Moralis-JS-SDK/demos/parse-server# yarn dev
warn: DeprecationWarning: The Parse Server option 'directAccess' default will change to 'true' in a future version. Additionally, the environment variable 'PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS' will be deprecated and renamed to 'PARSE_SERVER_DIRECT_ACCESS' in a future version; it is currently possible to use either one.
warn: DeprecationWarning: The Parse Server option 'enforcePrivateUsers' default will change to 'true' in a future version.
warn: DeprecationWarning: The Parse Server option 'allowClientClassCreation' default will change to 'false' in a future version.
Moralis Server is running on port 1337
error: Invalid function: "requestMessage" {"code":141,"stack":"Error: Invalid function: \"requestMessage\"\n    at handler (/root/moralis/Moralis-JS-SDK/node_modules/parse-server/src/Routers/FunctionsRouter.js:120:13)\n    at /root/moralis/Moralis-JS-SDK/node_modules/parse-server/src/PromiseRouter.js:72:20"}
```

I'm using the [moralis@2.11.0](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases/tag/moralis%402.11.0) version on the server side.

Do you know that?

2023-01-16 13:35 UTC, xactant approved these changes

2023-01-16 13:42 UTC, merged